In [1]:
import numpy

In [2]:
n=numpy.arange(27)

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

In [5]:
type(m)

numpy.ndarray

In [6]:
import cv2

In [7]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [8]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [9]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [11]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [12]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
